# core_rs.pyi

from logicsponge.core import DataItem

class Sender:
    def send(self, obj: DataItem) -> None: ...

class Receiver:
    def recv(self) -> DataItem: ...
    def history(self, index: int) -> DataItem: ...
    def __len__(self) -> int: ...
    def to_list(self) -> list[DataItem]: ...

def make_channel() -> tuple[Sender, Receiver]: ...
