"""logicsponge: A real-time data processing pipeline."""

from logicsponge.core.flow_backend import run_flow_graph
from logicsponge.core.graph import TermGraph
from logicsponge.core.logicsponge import (
    AddIndex,
    ConstantSourceTerm,
    DataItem,
    DataItemFilter,
    DataStream,
    Delay,
    Dump,
    FlatMapTerm,
    Flatten,
    FunctionTerm,
    Id,
    KeyFilter,
    KeyValueFilter,
    MergeToSingleStream,
    ParallelTerm,
    PPrint,
    Print,
    PrintKeys,
    Rename,
    SequentialTerm,
    SourceTerm,
    State,
    StatefulFunctionTerm,
    Stop,
    Term,
    parallel,
)

__all__ = [
    "AddIndex",
    "ConstantSourceTerm",
    "DataItem",
    "DataItemFilter",
    "DataStream",
    "Delay",
    "Dump",
    "FlatMapTerm",
    "Flatten",
    "FunctionTerm",
    "Id",
    "KeyFilter",
    "KeyValueFilter",
    "MergeToSingleStream",
    "PPrint",
    "ParallelTerm",
    "Print",
    "PrintKeys",
    "Rename",
    "SequentialTerm",
    "SourceTerm",
    "State",
    "StatefulFunctionTerm",
    "Stop",
    "Term",
    "TermGraph",
    "parallel",
    "run_flow_graph",
]
